apiVersion: apps/v1
kind: Deployment
metadata:
  name: rainbowdarkness-server-deployment
  labels:
    app: rainbowdarkness-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rainbowdarkness-server
  template:
    metadata:
      labels:
        app: rainbowdarkness-server
    spec:
      containers:
        - name: rainbowdarkness-server
          image: cayabyabrr/rainbowdarkness-server:latest
          ports:
            - containerPort: 32001


#Run this bottom part to run both api and service
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rainbowdarkness-server-deployment
  labels:
    app: rainbowdarkness-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rainbowdarkness-server
  template:
    metadata:
      labels:
        app: rainbowdarkness-server
    spec:
      containers:
        - name: rainbowdarkness-server
          image: cayabyabrr/rainbowdarkness-server:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rainbowdarkness-server-service
spec:
  selector:
    app: rainbowdarkness-server
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000