apiVersion: apps/v1
kind: Deployment
metadata:
  name: rainbowdarkness-server-deployment
  labels:
    app: rainbowdarkness-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rainbowdarkness-server
  template:
    metadata:
      labels:
        app: rainbowdarkness-server
    spec:
      containers:
        - name: rainbowdarkness-server
          image: cayabyabrr/rainbowdarkness-server:latest
          ports:
            - containerPort: 32001