apiVersion: v1
kind: Service
metadata:
  name: rainbowdarkness-server-service
spec:
  selector:
    app: rainbowdarkness-server
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer





# apiVersion: v1
# kind: Service
# metadata:
#   #name: rainbowdarkness-server
#   name: production
# spec:
#   ports:
#   - name: 8081
#   type: LoadBalancer
#   selector:
#     apps: rainbowdarkness-server